$f = 'c:\Users\den-a\SE\tailoring-management-user\src\user\Profile.jsx'
$lines = [System.IO.File]::ReadAllLines($f)

# Find handleDeclinePrice start (line 581, 0-based = 580)
# Replace lines 580-621 with new implementation
$newHandler = @(
  '  const handleDeclinePrice = async (item) => {',
  '    try {',
  '      const pricingFactors = item.pricing_factors || {};',
  '      const isAccessoriesDecline = pricingFactors.addAccessories === true && pricingFactors.enhancementRequest === true;',
  '',
  '      let reason = '''';',
  '      if (isAccessoriesDecline) {',
  '        reason = await new Promise((resolve) => {',
  '          const r = window.prompt(''Why are you declining the accessories price? (optional)'');',
  '          resolve(r || '''');',
  '        });',
  '        const isConfirmed = await confirm(',
  '          ''Declining the accessories price will send it back to the admin for review. Do you want to continue?'',',
  '          ''Decline Accessories Price'',',
  '          ''warning'',',
  '          { confirmText: ''Decline'', cancelText: ''Keep'' }',
  '        );',
  '        if (!isConfirmed) return;',
  '      } else {',
  '        const isConfirmed = await confirm(',
  '          ''Declining the updated price will cancel this order. Do you want to continue?'',',
  '          ''Confirm Price Decline'',',
  '          ''warning'',',
  '          { confirmText: ''Decline Price'', cancelText: ''Keep Order'' }',
  '        );',
  '        if (!isConfirmed) return;',
  '      }',
  '',
  '      const response = await fetch(`${API_URL}/orders/${item.order_item_id}/decline-price`, {',
  '        method: ''POST'',',
  '        headers: {',
  '          ''Content-Type'': ''application/json'',',
  '          ''Authorization'': `Bearer ${localStorage.getItem(''token'')}`,',
  '        },',
  '        body: JSON.stringify({ reason })',
  '      });',
  '',
  '      const result = await response.json();',
  '',
  '      if (result.success) {',
  '        if (result.isAccessoriesDecline) {',
  '          await alert(''Accessories price declined. The admin will review and adjust.'', ''Success'', ''success'');',
  '        } else {',
  '          await alert(''Price declined. Your order has been cancelled.'', ''Success'', ''success'');',
  '        }',
  '        const ordersResult = await getUserOrderTracking();',
  '        if (ordersResult.success) setOrders(ordersResult.data);',
  '      } else {',
  '        await alert(result.message || ''Failed to decline price'', ''Error'', ''error'');',
  '      }',
  '    } catch (error) {',
  '      await alert(''Error declining price. Please try again.'', ''Error'', ''error'');',
  '      console.error(''Error declining price:'', error);',
  '    }',
  '  };'
)

$newLines = $lines[0..579] + $newHandler + $lines[622..($lines.Count-1)]
[System.IO.File]::WriteAllLines($f, $newLines)
Write-Output 'Done'
