$f = 'c:\Users\den-a\SE\tailoring-management-user\src\admin\Customize.jsx'
$lines = [System.IO.File]::ReadAllLines($f)

# 1. Replace handleEnhancementPriceConfirm (lines 2934-2965, 0-based)
$newHandlerLines = @(
  '  const handleEnhancementPriceConfirm = async (item) => {',
  '    const target = item || enhancementPriceItem;',
  '    if (!target) return;',
  '',
  '    const pricingFactors = typeof target.pricing_factors === ''string''',
  '      ? JSON.parse(target.pricing_factors || ''{}'')',
  '      : (target.pricing_factors || {});',
  '',
  '    if (pricingFactors.addAccessories === true) {',
  '      setAccessoriesPriceItem(target);',
  '      setAccessoriesPrice('''');',
  '      setShowAccessoriesPriceModal(true);',
  '      setShowEnhancementViewModal(false);',
  '      return;',
  '    }',
  '',
  '    try {',
  '      setSavingEnhancementPrice(true);',
  '      const result = await updateCustomizationOrderItem(target.item_id, {',
  '        approvalStatus: ''accepted'',',
  '        finalPrice: parseFloat(target.final_price || 0),',
  '        pricingFactors: {',
  '          ...pricingFactors,',
  '          enhancementAdminAccepted: true,',
  '          enhancementPendingAdminReview: false,',
  '          enhancementAdminAcceptedAt: new Date().toISOString()',
  '        }',
  '      });',
  '      if (result.success) {',
  '        setEnhancementPriceItem(null);',
  '        setShowEnhancementViewModal(false);',
  '        showToast(''Enhancement accepted. Order moved to Accepted.'', ''success'');',
  '        loadCustomizationOrders();',
  '      } else {',
  '        showToast(result.message || ''Failed to accept enhancement'', ''error'');',
  '      }',
  '    } catch (err) {',
  '      showToast(''Failed to accept enhancement'', ''error'');',
  '    } finally {',
  '      setSavingEnhancementPrice(false);',
  '    }',
  '  };',
  '',
  '  const handleAccessoriesPriceSubmit = async () => {',
  '    if (!accessoriesPriceItem) return;',
  '    const price = parseFloat(accessoriesPrice);',
  '    if (isNaN(price) || price <= 0) {',
  '      showToast(''Please enter a valid accessories price'', ''error'');',
  '      return;',
  '    }',
  '    try {',
  '      setSavingEnhancementPrice(true);',
  '      const pricingFactors = typeof accessoriesPriceItem.pricing_factors === ''string''',
  '        ? JSON.parse(accessoriesPriceItem.pricing_factors || ''{}'')',
  '        : (accessoriesPriceItem.pricing_factors || {});',
  '      const baseFinalPrice = parseFloat(accessoriesPriceItem.final_price || 0);',
  '      const newFinalPrice = baseFinalPrice + price;',
  '      const result = await updateCustomizationOrderItem(accessoriesPriceItem.item_id, {',
  '        approvalStatus: ''price_confirmation'',',
  '        finalPrice: newFinalPrice,',
  '        adminNotes: `Accessories price: \u20b1${price.toFixed(2)}`,',
  '        pricingFactors: {',
  '          ...pricingFactors,',
  '          enhancementAdminAccepted: false,',
  '          enhancementPendingAdminReview: false,',
  '          enhancementAdminAcceptedAt: new Date().toISOString(),',
  '          accessoriesPrice: price.toFixed(2),',
  '          accessoriesBasePrice: baseFinalPrice.toFixed(2)',
  '        }',
  '      });',
  '      if (result.success) {',
  '        setShowAccessoriesPriceModal(false);',
  '        setAccessoriesPriceItem(null);',
  '        setAccessoriesPrice('''');',
  '        showToast(''Accessories price sent for customer confirmation.'', ''success'');',
  '        loadCustomizationOrders();',
  '      } else {',
  '        showToast(result.message || ''Failed to submit accessories price'', ''error'');',
  '      }',
  '    } catch (err) {',
  '      showToast(''Failed to submit accessories price'', ''error'');',
  '    } finally {',
  '      setSavingEnhancementPrice(false);',
  '    }',
  '  };'
)

# Replace lines 2934..2965 (0-based) with new handler
$lines = $lines[0..2933] + $newHandlerLines + $lines[2966..($lines.Count-1)]
[System.IO.File]::WriteAllLines($f, $lines)
Write-Output 'Handler replaced'
